# From: https://github.com/rkdarst/sphinx-actions-test/blob/master/.github/workflows/sphinx-build.yml

name: sphinx
on: [push, pull_request]

jobs:
  build-and-deploy:
    name: Build and gh-pages
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      # ^-- This gives info on matrix testing.
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # I don't know where the "run" thing is documented.
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Debugging information
        run: |
          git rev-parse --abbrev-ref HEAD
          git branch
          git branch -a
          git remote -v

      # Build
      - uses: ammaraskar/sphinx-problem-matcher@master
      - name: Build Sphinx docs
        run: |
          make dirhtml

      # The following supports building all branches and combining on
      # gh-pages
      - name: Clone old gh-pages
        run: |
          set -x
          ( git branch gh-pages remotes/origin/gh-pages && git clone . --branch=gh-pages _gh-pages/ ) || mkdir _gh-pages
          rm -rf _gh-pages/.git/
          mkdir -p _gh-pages/branch/
      - name: Copy new build (master)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          set -x
          find _gh-pages/ ! -mindepth 1 -path '_gh-pages/branch*' -delete
          rsync -a _build/dirhtml/ _gh-pages/
      - name: Copy new build (branch)
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          set -x
          rm -rf _gh-pages/branch/$(git rev-parse --abbrev-ref HEAD)
          rsync -a _build/dirhtml/ _gh-pages/branch/$(git rev-parse --abbrev-ref HEAD)
      - name: Delete old feature branches
        run: |
          set -x
          for brname in `ls _gh-pages/branch/` ; do
              if ! git show-ref remotes/origin/$brname ; then
                  echo "Removing $brname"
                  rm -r _gh-pages/branch/$brname/
              fi
          done

      # Deploy
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        #if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _gh-pages/
